// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import { loadEnvFiles } from './src/config/load-env-files';

loadEnvFiles();

export default defineConfig({
  schema: 'src/database/prisma/schema.prisma',
  migrations: {
    path: 'src/database/prisma/migrations',
    seed: 'ts-node src/database/prisma/seed.ts',
  },
  datasource: {
    url: process.env['POSTGRESQL_URL'],
  },
});
