apiVersion: 1

datasources:
  - name: MongoDB
    uid: mongodb
    type: haohanyang-mongodb-datasource
    access: proxy
    jsonData:
      connectionStringScheme: mongodb+srv
      host: $__env{GRAFANA_MONGODB_HOST}
      database: $__env{GRAFANA_MONGODB_DATABASE}
      authType: username-password
      username: $__env{GRAFANA_MONGODB_USER}
      authDb: admin
    secureJsonData:
      password: $__env{GRAFANA_MONGODB_PASSWORD}
    editable: true
