apiVersion: 1

datasources:
  - name: MongoDB
    uid: mongodb
    type: grafana-mongodb-datasource
    access: proxy
    jsonData:
      uri: mongodb://host.docker.internal:27017/mealio
    editable: true
