apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: $__env{GRAFANA_POSTGRES_HOST}
    user: $__env{GRAFANA_POSTGRES_USER}
    jsonData:
      database: $__env{GRAFANA_POSTGRES_DATABASE}
      sslmode: disable
      postgresVersion: 1800
    secureJsonData:
      password: $__env{GRAFANA_POSTGRES_PASSWORD}
    editable: true
