global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: mealio-producer
    metrics_path: /metrics
    static_configs:
      - targets: ['__PROMETHEUS_PRODUCER_TARGET__']
        labels:
          service: producer

  - job_name: mealio-consumer
    metrics_path: /metrics
    static_configs:
      - targets: ['__PROMETHEUS_CONSUMER_TARGET__']
        labels:
          service: consumer

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['__PROMETHEUS_PUSHGATEWAY_TARGET__']
