import type { Metadata } from 'next';
import { Geist_Mono, Noto_Sans_KR, Plus_Jakarta_Sans } from 'next/font/google';
import { AppRootFrame } from '@/components/layout/AppRootFrame';
import { AuthProvider } from '@/lib/auth/auth-context';
import { AppQueryClientProvider } from '@/lib/queries/query-client.provider';
import { ToastProvider } from '@/lib/toast';
import './globals.css';

const notoSansKr = Noto_Sans_KR({
  variable: '--font-noto-sans-kr',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
  weight: ['800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * 루트 레이아웃(서버 컴포넌트). 전역 클라이언트 Provider는 아래 순서로 감싼다.
 *
 * `AppQueryClientProvider` → `ToastProvider` → `AuthProvider` → `AppRootFrame`
 * (쿼리 캐시 `onError` 시점에 Toast 브리지가 등록되도록 Query가 바깥에 있음)
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${notoSansKr.variable} ${geistMono.variable} ${plusJakartaSans.variable}`}
    >
      <body className="antialiased">
        <AppQueryClientProvider>
          <ToastProvider>
            <AuthProvider>
              <AppRootFrame>{children}</AppRootFrame>
            </AuthProvider>
          </ToastProvider>
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
