import { KAFKA_TOPICS } from '@mealio/shared';
import { CONSUMER_GROUPS } from '../../constants/consumer-groups.constants';

const TOPIC_TO_CONSUMER_GROUP: Record<string, string> = {
  [KAFKA_TOPICS.CHATBOT_REQUESTS]: CONSUMER_GROUPS.CHATBOT,
  [KAFKA_TOPICS.USER_EVENTS]: CONSUMER_GROUPS.USER_EVENTS,
  [KAFKA_TOPICS.ACTIVITY_EVENTS]: CONSUMER_GROUPS.ACTIVITY_EVENTS,
  [KAFKA_TOPICS.CACHE_INVALIDATION]: CONSUMER_GROUPS.CACHE_INVALIDATION,
  [KAFKA_TOPICS.RECIPE_INGESTION_RETRIEVED]:
    CONSUMER_GROUPS.RECIPE_INGESTION_PERSIST,
};

export function getConsumerGroupForTopic(topic: string): string {
  return TOPIC_TO_CONSUMER_GROUP[topic] ?? 'unknown';
}
